'use strict';
/* =================================================================
   ほしぞらさんぽ — 画面の文言（main.js が使う）
   ja = おとな用、kana = ひらがなモード（無い文言は ja を使う）、en = 英語版（en/index.html）
   値は文字列か、引数を受け取って文字列を返す関数。HTML 側の固定の文言は各 index.html に書く
   ================================================================= */
const TEXT = {
  ja: {
    correct:'○ せいかい！', wrong:'✕ ざんねん',
    dirs:['北','北東','東','南東','南','南西','西','北西'],
    dirsLong:['北','北東','東','南東','南','南西','西','北西'],
    localTime:'（現地時刻）', traveling:'（時間たび中）',
    where:(place,dir)=>`${place}の空 ・ ${dir}を向いています`,
    conKind:c=>c.kana+'ざ',
    seasonChip:s=>`${s}の星座`,
    upNow:'いま空に見えています', below:'いまは地平線の下',
    starMag:(mag,ly)=>`${mag}等${ly?' ・ '+ly+'光年':''}`,
    funLabel:'まめちしき',
    zukanLink:c=>`${c.jp}の見つけ方・図鑑ページ →`,
    zukanOfStar:c=>`${c.jp}の図鑑ページ →`,
    starKind:'恒星',
    starStory:ly=>`${ly?`いま見えている光は、約${ly}年前にこの星を出た光です。`:''}星の色は表面温度で決まります。<b style="color:#a8c0ff">青い星ほど高温</b>、<b style="color:#ff9d68">赤い星ほど低温</b>です。`,
    tempHot:'高温（約30,000度〜）', tempCool:'低温（約3,000度）',
    magChip:m=>`${m}等星`, lyChip:ly=>`約${ly}光年`,
    sunWarn:'ぜったいに直接見ない', moonAge:a=>`月齢 ${a.toFixed(1)}`,
    moonDist:km=>`地球から 約${Math.round(km/1000)/10}万km`,
    moonLit:(pct,waxing)=>`いまの月は ${pct}% が光っています。${waxing?'これから満月に向かって、毎日少しずつふくらんでいきます。':'これから新月に向かって、毎日少しずつ細くなっていきます。'}`,
    planet:'惑星', satellite:'衛星',
    planetMag:m=>`${m}等`,
    planetDist:(au)=>`地球から 約${(au*1.496).toFixed(1)}億km（光で約${Math.round(au*8.317)}分）`,
    notNight:'いまは空が明るくて星が見えません。「時間たび」で夜にしてから挑戦してね',
    fewCons:'いま空に出ている星座が少ないよ。時間を動かしてみてね',
    quizQ:c=>`「<b>${c.jp}</b>」をさがしてタップ！`,
    quizPerfect:'パーフェクト！きみは星はかせだ！', quizGood:'すごい！あと少しでパーフェクト！',
    quizAgain:'また挑戦してね。星座線と名まえをONにして予習しよう！',
    quizCount:(sc,n)=>`${n}問中 <b style="color:var(--gold)">${sc}問</b> 正解。`, quizTitle:'クイズの結果',
    asterToast:'夏・冬の大三角と春の大曲線。明るい星をつなぐ星さがしの道しるべです',
    kidsToast:'おとなモード：くわしい解説に切りかえました',
    redToast:'赤いライト：暗さに慣れた目を守ります。画面の明るさも下げると効果的です',
    playToast:x=>`時間を${x}倍の速さで進めています。星がまわる「日周運動」を見てみよう`,
    placeBtn:name=>'場所: '+name, pause:'⏸ とめる', play:'▶ 早送り', speed:x=>`はやさ ×${x}`,
    southToast:'シドニー（南半球）！太陽は北の空を通り、星は南の空を中心に回ります。南十字星もさがしてみて',
    movedToast:name=>`${name}の空に移動しました`,
    noGeo:'この端末では位置情報が使えません', geoFail:'位置情報を取得できませんでした。端末の設定で許可してください',
    geoOk:'いまいる場所の空にしました', here:'いまいる場所',
    dayJump:'いまは昼間なので、今夜21時の空にワープしました🌙（「時間たび」→「いまに戻る」で現在へ）',
    linkedToast:(p,place)=>`${+p.month}月${+p.day}日 ${+p.hour}時${p.minute==='00'?'':p.minute+'分'}の${place}の空です（「時間たび」→「いまに戻る」で現在へ）`,
    focusToast:(c,p,place)=>`${c.jp}がよく見える ${+p.month}月${+p.day}日 21時の${place}の空です`,
  },
  kana: {
    dirs:['きた','','ひがし','','みなみ','','にし',''],
    dirsLong:['きた','ほくとう','ひがし','なんとう','みなみ','なんせい','にし','ほくせい'],
    localTime:'（げんちの じかん）', traveling:'（じかんたび ちゅう）',
    where:(place,dir)=>`${place}の そら ・ ${dir}を むいているよ`,
    conKind:()=>'せいざ',
    seasonChip:s=>`${s}の せいざ`,
    upNow:'いま みえているよ', below:'いまは ちへいせんの した',
    starMag:(mag,ly)=>`${mag}とうせい${ly?' ・ やく'+ly+'こうねん':''}`,
    zukanLink:()=>'ずかんで もっと みる →', zukanOfStar:()=>'ずかんで もっと みる →',
    starKind:'ほし',
    starStory:ly=>`${ly?`いま みえている ひかりは、やく${ly}ねんまえに この ほしを でた ひかりだよ。`:''}あおい ほしは とっても あつい ほし。あかい ほしは すこし つめたい ほしなんだ。`,
    tempHot:'あつい ほし（あおい）', tempCool:'つめたい ほし（あかい）',
    magChip:m=>`${m}とうせい`, lyChip:ly=>`やく${ly}こうねん`,
    sunWarn:'ちょくせつ みないでね', moonAge:a=>`つきの としは ${a.toFixed(0)}`,
    moonDist:km=>`ちきゅうから やく${Math.round(Math.round(km/1000)/10)}まん キロ`,
    moonLit:(pct,waxing)=>waxing?'これから まいにち すこしずつ ふとって いくよ。':'これから まいにち すこしずつ ほそく なって いくよ。',
    planet:'わくせい', satellite:'えいせい',
    planetMag:m=>`${m}とうせい`,
    planetDist:au=>`ちきゅうから やく${(au*1.496).toFixed(1)}おく キロ`,
    notNight:'いまは ひるまで ほしが みえないよ。「じかんたび」で よるに してから ちょうせん！',
    fewCons:'いま でている せいざが すくないよ。じかんを うごかしてみてね',
    quizQ:c=>`「<b>${c.kana}ざ</b>」を さがして タップ！`,
    quizPerfect:'ぜんぶ せいかい！きみは ほしはかせだ！', quizGood:'すごい！あと すこしで ぜんぶ せいかい！',
    quizAgain:'また ちょうせん してみてね！',
    quizCount:(sc,n)=>`${n}もんちゅう <b style="color:var(--gold)">${sc}もん</b> せいかい。`, quizTitle:'クイズの けっか',
    asterToast:'あかるい ほしを つなぐと、おおきな さんかくが できるよ',
    kidsToast:'ひらがなモード：かんじを つかわない おはなしに きりかえたよ',
    redToast:'あかい ライト：くらい ところでも めが まぶしく ならないよ',
    playToast:()=>'じかんを はやおくり ちゅう。ほしが ぐるっと まわるよ',
    placeBtn:name=>'ばしょ: '+name, play:'▶ はやおくり',
    southToast:'シドニーは みなみはんきゅう。みなみじゅうじせいを さがしてみよう！',
    movedToast:name=>`${name}の そらに いどう したよ`,
    noGeo:'いる ばしょが わからなかったよ', geoFail:'いる ばしょが わからなかったよ',
    geoOk:'いま いる ばしょの そらに したよ', here:'いま いる ばしょ',
    dayJump:'いまは ひるま なので、こんやの 9じの そらに ワープしたよ🌙',
    linkedToast:p=>`${+p.month}がつ${+p.day}にち ${+p.hour}じの そらだよ`,
    focusToast:(c,p)=>`${c.kana}ざが よく みえる ${+p.month}がつ${+p.day}にち よる9じの そらだよ`,
  },
  en: {
    correct:'✓ Correct!', wrong:'✕ Not quite',
    dirs:['N','NE','E','SE','S','SW','W','NW'],
    dirsLong:['north','northeast','east','southeast','south','southwest','west','northwest'],
    localTime:'', traveling:' · time travel',
    where:(place,dir)=>`Sky over ${place} · facing ${dir}`,
    conKind:()=>'Constellation',
    seasonChip:s=>s,
    upNow:'Above the horizon now', below:'Below the horizon now',
    starMag:(mag,ly)=>`mag ${mag}${ly?' · '+ly+' ly':''}`,
    funLabel:'Did you know?',
    mythNote:'The story and notes for this constellation are in Japanese only for now.',
    zukanLink:()=>'Constellation page (in Japanese) →',
    zukanOfStar:()=>'Constellation page (in Japanese) →',
    starKind:'Star',
    starStory:ly=>`${ly?`The light you see left this star about ${ly} years ago. `:''}A star’s color shows its surface temperature: <b style="color:#a8c0ff">blue stars are hotter</b>, <b style="color:#ff9d68">red stars are cooler</b>.`,
    tempHot:'Hot (about 30,000 K)', tempCool:'Cool (about 3,000 K)',
    magChip:m=>`Magnitude ${m}`, lyChip:ly=>`About ${ly} light-years`,
    sunWarn:'Never look at it directly', moonAge:a=>`Age ${a.toFixed(1)} days`,
    moonDist:km=>`About ${(Math.round(km/1000)*1000).toLocaleString('en-US')} km from Earth`,
    moonLit:(pct,waxing)=>`${pct}% of the Moon is lit. ${waxing?'It grows a little each night until the full moon.':'It shrinks a little each night until the new moon.'}`,
    planet:'Planet', satellite:'Natural satellite',
    planetMag:m=>`Magnitude ${m}`,
    planetDist:au=>`About ${Math.round(au*149.6).toLocaleString('en-US')} million km away (light takes about ${Math.round(au*8.317)} min)`,
    notNight:'The sky is too bright for stars right now. Use Time to make it night, then try again.',
    fewCons:'Only a few constellations are up right now. Try moving the time.',
    quizQ:c=>`Find <b>${c.en}</b> and tap it!`,
    quizPerfect:'Perfect! You’re a star expert!', quizGood:'Great! Almost perfect!',
    quizAgain:'Try again. Turn on Lines and Names to practice first!',
    quizCount:(sc,n)=>`<b style="color:var(--gold)">${sc} of ${n}</b> correct. `, quizTitle:'Quiz result',
    asterToast:'The Summer and Winter Triangles and the Arc to Arcturus and Spica: bright-star shapes that help you find your way.',
    redToast:'Red light keeps your eyes used to the dark. Turning down screen brightness helps too.',
    playToast:x=>`Time is running ${x}× faster. Watch the stars turn across the sky.`,
    placeBtn:name=>'Place: '+name, pause:'⏸ Pause', play:'▶ Fast-forward', speed:x=>`Speed ×${x}`,
    southToast:'Southern Hemisphere: the Sun crosses the northern sky, and the stars turn around a point in the south. Look for the Southern Cross (Crux).',
    movedToast:name=>`Now showing the sky over ${name}`,
    noGeo:'Location is not available on this device.', geoFail:'Couldn’t get your location. Allow location access in your device settings.',
    geoOk:'Now showing the sky from your location', here:'Your location', custom:'Custom place',
    badCoords:'Enter a latitude from −90 to 90 and a longitude from −180 to 180.',
    dayJump:'It’s daytime, so here is the sky at 9 p.m. tonight 🌙 (Time → Back to now returns to the present)',
    linkedToast:(p,place)=>`The sky over ${place} on ${MONTHS_EN[+p.month-1]} ${+p.day} at ${clock12(p)} (Time → Back to now returns to the present)`,
    focusToast:(c,p,place)=>`${c.en} is well placed at 9 p.m. on ${MONTHS_EN[+p.month-1]} ${+p.day} from ${place}`,
  },
};
const MONTHS_EN=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
/** 現地時刻の部品（main.js の localParts）→ 9:05 p.m. */
const clock12=p=>`${(+p.hour%12)||12}:${p.minute} ${+p.hour<12?'a.m.':'p.m.'}`;
if(typeof module!=='undefined') module.exports={TEXT,MONTHS_EN};
